IRRELEVANT_WORDS_IN_ORIGIN = [
    "honey",
    "washed",
    "espressoekspres / kawiarka",
    "nan",
    "przelew",
    "pulped natural",
    "espresso",
    "Kuba",
    "natural",
    "metody alternatywne / przelewowe",
    "carbonic macerationwashed",
    "omniroast",
    "LaCava Certified 350g kawa ziarnista",
    "LaCava Certified 1 kg kawa ziarnista",
    "średnie",
]

COLORS = ["yellow", "red", "pink"]

VARIETY_MAPPING = {
    "Mundo Nuovo": 'Mundo Novo',
    "Catimor": "Catimor 129",
    "Catuaí": "Catuai",
    "Topazio": "",
    "Catucai": "catuai",
    "typica / coś fajnego": "typica",
    "Catuacai 2Sl": "catuai",
    "Paraiso": "Catimor 129",
    "Local Heirloom": "",
    "Tabi": "",
    "Obatã": "Obata",
    "-": "",
    "proces": "",
    "Kent": "",
    "Sudan Rume": "Heirloom",
    "pulped natural": "",
    "Laurina": "",
    "Chiroso": "Caturra",
    "Ombligon": "Pacamara",
    "Rosado": "Bourbon",
    "Ateng Super": "",
    "H1": "",
    "Ruiru11": "Ruiru 11",
    "mix": "",
    "Ateng": "",
    "Bor Bor": "",
    "Timor": "Catimor 129",
    "Sl18": "sl28",
    "Rosado(a.k.a. Pink Bourbon": "Bourbon",
    "a.k.a. Colombia Rosado)": "Bourbon",
    "Colombia": "Catuai",
    "Gesha": "Geisha",
    "Boubon": "Bourbon",
    "Catui": "Catuai",
    "Tim Tim": "",
    "Gayo 1": "",
    "gibirinna 74110": "",
    "serto 74112": "",
    "Mokka": "Heirloom",
    "SLN 9": "",
    "Caturro Chiroso": "Caturra",
    "Baitan": "Batian",
    "N39": "",
    "Robusta": "Nemaya",
    "Sumatra": "",
    "Heriloom": "Heirloom",
    "mix odmian": "",
    "Jarc": "",
    "Ruby": "",
    "IPR100": "",
    "Bourbon Aji": "Bourbon",
    "Andung Sari": "",
    "Sigarar Utang": "",
    "BourbonJacksonMbirizi": "Bourbon",
    "castillo": '',
    "colombia": '',
    "ana café 14": 'Anacafe 14',
    "Ana Café 14": 'Anacafe 14',
    'Castillo': ''
}
